apiVersion: apps/v1
kind: Deployment
IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
IMAGE="ghcr.io/thandrix_systems/thandrix_app:${IMAGE_TAGS}"
metadata:
  name: thandrix-app
  labels:
    app: thandrix-app
spec:
  replicas: 1    
  selector:
    matchLabels:
      app: thandrix-app
  template:
    metadata:
      labels:
        app: thandrix-app
    spec:
      containers:
        - name: thandrix-springboot
          image: ${IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"          