name: github-pipelines

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  security-events: write  
  packages: write
  contents: read 

jobs:
  ci-pipeline:
    uses: thandrix-systems/reusable-workflows/.github/workflows/ci-pipelines.yml@main
    with:
      run_codeql: true
      run_sonarqube: true
      run_publish_to_github_container_registry: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy-to-kubernetes:
    needs: ci-pipeline
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chlmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: SetConfigure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl version
          kubectl get nodes

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f manifests/deployment.yaml
      #     kubectl apply -f manifests/service.yaml    
