name: github-pipelines
#Trigger workflow on pull requests and pushes to main, dev, and feature branches

on:
  push:
    branches:
      - main
      - dev
      - feature/*
      
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  security-events: write  
  packages: write
  contents: read 

jobs:
  ci-pipeline:
    uses: thandrix-systems/reusable-workflows/.github/workflows/ci-pipelines.yml@main
    with:
      run_codeql: true
      run_sonarqube: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
